name: deployment workflow
on: push
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello there"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v5
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{ hashFiles('**/package.lock.json') }}
      - name: download dependencies
        run: npm ci
      - name: test
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: get code
        uses: actions/checkout@v5
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-node-modules-${{ hashFiles('**/package.lock.json') }}
      - name: download dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: output file name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo "script-file={}" >> $GITHUB_OUTPUT ';'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get-artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: print artifact files
        run: |
          ls
          echo "deploying"
      - name: print script file name
        run: echo "${{ needs.build.outputs.script-file }}"
